<a href="https://colab.research.google.com/github/Siri2191/Project-Cartola/blob/main/Score_por_times.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
cartola_acumulado = pd.read_excel('partidas_acumulado.xlsx')
cartola_acumulado.head()

,Unnamed: 0,Rodada,CasaID,VisitanteID,PlacarCasa,PlacarVisitante,ano,Resultado
0,0,1,São Paulo - SP,Flamengo - RJ,2,1,2015,CASA
1,1,1,Palmeiras - SP,Atlético - MG,2,2,2015,EMPATE
2,2,1,Fluminense - RJ,Joinville - SC,1,0,2015,CASA
3,3,1,Vasco da Gama - RJ,Goiás - GO,0,0,2015,EMPATE
4,4,1,Grêmio - RS,Ponte Preta - SP,3,3,2015,EMPATE

In [ ]:
cartola_acumulado.drop(columns='Unnamed: 0', inplace=True)
cartola_acumulado.drop_duplicates()
cartola_acumulado

,Rodada,CasaID,VisitanteID,PlacarCasa,PlacarVisitante,ano,Resultado
0,1,São Paulo - SP,Flamengo - RJ,2,1,2015,CASA
1,1,Palmeiras - SP,Atlético - MG,2,2,2015,EMPATE
2,1,Fluminense - RJ,Joinville - SC,1,0,2015,CASA
3,1,Vasco da Gama - RJ,Goiás - GO,0,0,2015,EMPATE
4,1,Grêmio - RS,Ponte Preta - SP,3,3,2015,EMPATE
...,...,...,...,...,...,...,...
2275,38,Internacional - RS,Corinthians - SP,0,0,2020,EMPATE
2276,38,Bahia - BA,Santos - SP,2,0,2020,CASA
2277,38,Atlético - PR,Sport - PE,2,0,2020,CASA
2278,38,Ceará - CE,Botafogo - RJ,2,1,2020,CASA
2279,38,Atlético - GO,Coritiba - PR,3,1,2020,CASA

In [ ]:
cartola_acumulado.groupby('Resultado')['Resultado'].count()

Resultado
CASA         1119
EMPATE        622
VISITANTE     539
Name: Resultado, dtype: int64

Times que jogam em casa, ganham mais ds que jogam fora

In [ ]:
vitoria_em_casa = cartola_acumulado.query('CasaID=="Flamengo - RJ" & Resultado=="CASA"')['Resultado'].count()
vitoria_em_casa

72

In [ ]:
vitoria_como_visitante = cartola_acumulado.query('VisitanteID=="Flamengo - RJ" & Resultado=="VISITANTE"')['Resultado'].count()
vitoria_como_visitante

49

In [ ]:
total_vitorias = vitoria_como_visitante+vitoria_em_casa
total_vitorias

121

In [ ]:
total_partidas_times = cartola_acumulado.query('VisitanteID=="Flamengo - RJ" or CasaID=="Flamengo - RJ"')['Resultado'].count()
total_partidas_times

228

In [ ]:
empates_como_visitante = cartola_acumulado.query('VisitanteID=="Flamengo - RJ" & Resultado=="EMPATE"')['Resultado'].count()
empates_como_visitante

27

In [ ]:
empates_como_casa=cartola_acumulado.query('CasaID=="Flamengo - RJ" & Resultado=="EMPATE"')['Resultado'].count()
empates_como_casa

25

In [ ]:


total_empates = empates_como_casa + empates_como_visitante
total_empates

52

In [ ]:
derrota_em_casa = cartola_acumulado.query('CasaID=="Flamengo - RJ" & Resultado=="VISITANTE"')['Resultado'].count()
derrota_em_casa

17

In [ ]:
derrota_como_visitante = cartola_acumulado.query('VisitanteID=="Flamengo - RJ" & Resultado=="CASA"')['Resultado'].count()
derrota_como_visitante

38

In [ ]:
total_derrota = derrota_como_visitante + derrota_em_casa
total_derrota

55

In [ ]:


cartola_acumulado['CasaID'].unique()

array(['São Paulo - SP', 'Palmeiras - SP', 'Fluminense - RJ',
       'Vasco da Gama - RJ', 'Grêmio - RS', 'Cruzeiro - MG', 'Avaí - SC',
       'Atlético - PR', 'Sport - PE', 'Chapecoense - SC',
       'Corinthians - SP', 'Santos - SP', 'Ponte Preta - SP',
       'Flamengo - RJ', 'Internacional - RS', 'Atlético - MG',
       'Figueirense - SC', 'Coritiba - PR', 'Goiás - GO',
       'Joinville - SC', 'América - MG', 'Santa Cruz - PE',
       'Vitória - BA', 'Botafogo - RJ', 'Bahia - BA', 'Atlético - GO',
       'Paraná - PR', 'Ceará - CE', 'CSA', 'Fortaleza', 'Bragantino - SP'],
      dtype=object)

In [ ]:
cartola_acumulado['Resultado'].unique()

array(['CASA', 'EMPATE', 'VISITANTE'], dtype=object)

In [ ]:
lista_times = ['São Paulo - SP', 'Palmeiras - SP', 'Fluminense - RJ',
       'Vasco da Gama - RJ', 'Grêmio - RS', 'Cruzeiro - MG', 'Avaí - SC',
       'Atlético - PR', 'Sport - PE', 'Chapecoense - SC',
       'Corinthians - SP', 'Santos - SP', 'Ponte Preta - SP',
       'Flamengo - RJ', 'Internacional - RS', 'Atlético - MG',
       'Figueirense - SC', 'Coritiba - PR', 'Goiás - GO',
       'Joinville - SC', 'América - MG', 'Santa Cruz - PE',
       'Vitória - BA', 'Botafogo - RJ', 'Bahia - BA', 'Atlético - GO',
       'Paraná - PR', 'Ceará - CE', 'CSA', 'Fortaleza', 'Bragantino - SP']

dicionario = {}

for item in lista_times:
  total_partidas_times = cartola_acumulado.query('VisitanteID=="{}" or CasaID=="{}"'.format(item,item))['Resultado'].count()
  vitoria_em_casa = cartola_acumulado.query('CasaID=="{}" & Resultado=="CASA"'.format(item))['Resultado'].count()
  vitoria_como_visitante = cartola_acumulado.query('VisitanteID=="{}" & Resultado=="VISITANTE"'.format(item))['Resultado'].count()
  total_vitorias = vitoria_como_visitante+vitoria_em_casa
  empates_como_visitante = cartola_acumulado.query('VisitanteID=="{}" & Resultado=="EMPATE"'.format(item))['Resultado'].count()
  empates_como_casa=cartola_acumulado.query('CasaID=="{}" & Resultado=="EMPATE"'.format(item))['Resultado'].count()
  total_empates = empates_como_casa + empates_como_visitante
  derrota_em_casa = cartola_acumulado.query('CasaID=="{}" & Resultado=="VISITANTE"'.format(item))['Resultado'].count()
  derrota_como_visitante = cartola_acumulado.query('VisitanteID=="{}" & Resultado=="CASA"'.format(item))['Resultado'].count()
  total_derrota = derrota_como_visitante + derrota_em_casa
  dicionario[item] = (total_partidas_times,
                      vitoria_em_casa,
                      vitoria_como_visitante,
                      total_vitorias,empates_como_visitante,
                      empates_como_casa,total_empates,derrota_em_casa,
                      derrota_como_visitante,total_derrota)
  score_por_times = pd.DataFrame(dicionario).transpose()

rename_columns={'index':'times',0:'total_partidas',1:'vitorias_em_casa',2:'vitoria_como_visitante',
                3:'total_vitorias',4:'empates_como_visitantes',5:'empates_em_casa',
                6:'total_empates',7:'derrotas_em_casa',8:'derrotas_como_visitante',9:'total_derrotas'}

score_por_times.rename(columns=rename_columns,inplace=True)
score_por_times

,total_partidas,vitorias_em_casa,vitoria_como_visitante,total_vitorias,empates_como_visitantes,empates_em_casa,total_empates,derrotas_em_casa,derrotas_como_visitante,total_derrotas
São Paulo - SP,228,60,35,95,29,40,69,14,50,64
Palmeiras - SP,228,73,42,115,34,25,59,16,38,54
Fluminense - RJ,228,51,29,80,28,33,61,30,57,87
Vasco da Gama - RJ,190,36,21,57,30,29,59,30,44,74
Grêmio - RS,228,69,32,101,41,25,66,20,41,61
Cruzeiro - MG,190,42,23,65,26,32,58,21,46,67
Avaí - SC,114,14,9,23,11,23,34,20,37,57
Atlético - PR,228,67,27,94,28,25,53,22,59,81
Sport - PE,190,46,16,62,22,25,47,24,57,81
Chapecoense - SC,190,40,18,58,32,25,57,30,45,75
Corinthians - SP,228,65,33,98,30,36,66,13,51,64
Santos - SP,228,72,30,102,32,28,60,14,52,66
Ponte Preta - SP,114,31,6,37,21,10,31,16,30,46
Flamengo - RJ,228,72,49,121,27,25,52,17,38,55
Internacional - RS,190,58,23,81,27,25,52,12,45,57
Atlético - MG,228,68,33,101,37,20,57,26,44,70
Figueirense - SC,76,13,5,18,8,17,25,8,25,33
Coritiba - PR,152,26,13,39,19,26,45,24,44,68
Goiás - GO,114,24,10,34,13,14,27,19,34,53
Joinville - SC,38,6,1,7,3,8,11,5,15,20
América - MG,76,15,2,17,7,11,18,12,29,41
Santa Cruz - PE,38,7,1,8,5,2,7,10,13,23
Vitória - BA,114,18,14,32,15,14,29,25,28,53
Botafogo - RJ,190,40,21,61,25,22,47,33,49,82
Bahia - BA,152,36,13,49,23,21,44,19,40,59
Atlético - GO,76,10,11,21,9,14,23,14,18,32
Paraná - PR,38,3,0,3,2,10,12,6,17,23
Ceará - CE,114,22,11,33,15,19,34,16,31,47
CSA,38,6,2,8,3,5,8,8,14,22
Fortaleza,76,19,6,25,11,8,19,11,21,32
Bragantino - SP,38,10,3,13,9,5,14,4,7,11

In [ ]:
score_por_times = score_por_times.reset_index()
score_por_times.rename(columns={'index':'times'},inplace=True)
score_por_times

,times,total_partidas,vitorias_em_casa,vitoria_como_visitante,total_vitorias,empates_como_visitantes,empates_em_casa,total_empates,derrotas_em_casa,derrotas_como_visitante,total_derrotas
0,São Paulo - SP,228,60,35,95,29,40,69,14,50,64
1,Palmeiras - SP,228,73,42,115,34,25,59,16,38,54
2,Fluminense - RJ,228,51,29,80,28,33,61,30,57,87
3,Vasco da Gama - RJ,190,36,21,57,30,29,59,30,44,74
4,Grêmio - RS,228,69,32,101,41,25,66,20,41,61
5,Cruzeiro - MG,190,42,23,65,26,32,58,21,46,67
6,Avaí - SC,114,14,9,23,11,23,34,20,37,57
7,Atlético - PR,228,67,27,94,28,25,53,22,59,81
8,Sport - PE,190,46,16,62,22,25,47,24,57,81
9,Chapecoense - SC,190,40,18,58,32,25,57,30,45,75
10,Corinthians - SP,228,65,33,98,30,36,66,13,51,64
11,Santos - SP,228,72,30,102,32,28,60,14,52,66
12,Ponte Preta - SP,114,31,6,37,21,10,31,16,30,46
13,Flamengo - RJ,228,72,49,121,27,25,52,17,38,55
14,Internacional - RS,190,58,23,81,27,25,52,12,45,57
15,Atlético - MG,228,68,33,101,37,20,57,26,44,70
16,Figueirense - SC,76,13,5,18,8,17,25,8,25,33
17,Coritiba - PR,152,26,13,39,19,26,45,24,44,68
18,Goiás - GO,114,24,10,34,13,14,27,19,34,53
19,Joinville - SC,38,6,1,7,3,8,11,5,15,20
20,América - MG,76,15,2,17,7,11,18,12,29,41
21,Santa Cruz - PE,38,7,1,8,5,2,7,10,13,23
22,Vitória - BA,114,18,14,32,15,14,29,25,28,53
23,Botafogo - RJ,190,40,21,61,25,22,47,33,49,82
24,Bahia - BA,152,36,13,49,23,21,44,19,40,59
25,Atlético - GO,76,10,11,21,9,14,23,14,18,32
26,Paraná - PR,38,3,0,3,2,10,12,6,17,23
27,Ceará - CE,114,22,11,33,15,19,34,16,31,47
28,CSA,38,6,2,8,3,5,8,8,14,22
29,Fortaleza,76,19,6,25,11,8,19,11,21,32
30,Bragantino - SP,38,10,3,13,9,5,14,4,7,11

In [ ]:

score_por_times.to_excel('score_por_time.xlsx', index='False')
score_por_times.to_csv('score_por_times.csv', index = 'False')